### ISSUE TITLE
Duplicity backup to Google Docs now results in 404 error

### ISSUE THREAD

**Issue by michaelslec** [zertrin/duplicity-backup#95]
When running duplicity.sh -b, I know get a 404 error saying:

    ClientLoginFailed: Server responded to ClientLogin request: 404, https://developers.google.com/accounts/docs/AuthForInstalledApps

I believe it may be because Google OAuth1 is now officially deprecated? I'm not quite sure. Some new form of authentication may be required, or it's totally on my end. Here's the whole output I get when I Run duplicity:

    Traceback (most recent call last):
      File "/usr/bin/duplicity", line 1523, in <module>
        with_tempdir(main)
      File "/usr/bin/duplicity", line 1517, in with_tempdir
        fn()
      File "/usr/bin/duplicity", line 1355, in main
        action = commandline.ProcessCommandLine(sys.argv[1:])
      File "/usr/lib/python2.7/site-packages/duplicity/commandline.py", line 1101, in ProcessCommandLine
        backup, local_pathname = set_backend(args[0], args[1])
      File "/usr/lib/python2.7/site-packages/duplicity/commandline.py", line 992, in set_backend
        globals.backend = backend.get_backend(bend)
      File "/usr/lib/python2.7/site-packages/duplicity/backend.py", line 223, in get_backend
        obj = get_backend_object(url_string)
      File "/usr/lib/python2.7/site-packages/duplicity/backend.py", line 209, in get_backend_object
        return factory(pu)
      File "/usr/lib/python2.7/site-packages/duplicity/backends/gdocsbackend.py", line 54, in __init__
        self._authorize(parsed_url.username + '@' + parsed_url.hostname, self.get_password())
      File "/usr/lib/python2.7/site-packages/duplicity/backends/gdocsbackend.py", line 134, in _authorize
        captcha_response=captcha_response)
      File "/usr/lib/python2.7/site-packages/gdata/client.py", line 441, in client_login
        captcha_token=captcha_token, captcha_response=captcha_response)  
      File "/usr/lib/python2.7/site-packages/gdata/client.py", line 373, in request_client_login_token
        response, ClientLoginFailed, response_body)
    ClientLoginFailed: Server responded to ClientLogin request: 404,        https://developers.google.com/accounts/docs/AuthForInstalledApps

    Traceback (most recent call last):
      File "/usr/bin/duplicity", line 1523, in <module>
        with_tempdir(main)
      File "/usr/bin/duplicity", line 1517, in with_tempdir
        fn()
      File "/usr/bin/duplicity", line 1355, in main
        action = commandline.ProcessCommandLine(sys.argv[1:])
      File "/usr/lib/python2.7/site-packages/duplicity/commandline.py", line 1093, in  ProcessCommandLine
        globals.backend = backend.get_backend(args[0])
      File "/usr/lib/python2.7/site-packages/duplicity/backend.py", line 223, in get_backend
        obj = get_backend_object(url_string)
      File "/usr/lib/python2.7/site-packages/duplicity/backend.py", line 209, in get_backend_object
        return factory(pu)
      File "/usr/lib/python2.7/site-packages/duplicity/backends/gdocsbackend.py", line 54, in __init__
        self._authorize(parsed_url.username + '@' + parsed_url.hostname, self.get_password())
      File "/usr/lib/python2.7/site-packages/duplicity/backends/gdocsbackend.py", line 134, in _authorize
        captcha_response=captcha_response)
      File "/usr/lib/python2.7/site-packages/gdata/client.py", line 441, in client_login
        captcha_token=captcha_token, captcha_response=captcha_response)
      File "/usr/lib/python2.7/site-packages/gdata/client.py", line 373, in request_client_login_token
        response, ClientLoginFailed, response_body)
    ClientLoginFailed: Server responded to ClientLogin request: 404,     https://developers.google.com/accounts/docs/AuthForInstalledApps

Thank you!

**Comment by zertrin** [comment]
This issue concerns primarily duplicity, not duplicity-backup.sh, which is only a wrapper around duplicity. Please report this upstream (see the duplicity mailing-lists https://lists.nongnu.org/mailman/listinfo/duplicity-talk or the duplicity bug-tracker https://launchpad.net/duplicity .)

Probably some adaption will be needed to make the new authentication requirements of Google compatible with this script. But first we need to see how this is possible when using duplicity directly (without this wrapper).

As I don't use Google Storage and have no plan in using it, feel free to troubleshoot this and submit a pull request when you have found a solution, or wait until someone else does ;)

**Comment by zertrin** [comment]
Closing for lack of feedback. Feel free to reopen if needed.
